### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by underTheDark** [yangzongzhuan/RuoYi#100]
第一期使用打包是没问题的，第二期使用框架又重新下载了前端源码，后端没有变。然后前端这边布局开启 TopNav,然后二期本地运行没事，打包后提示找不到组件模块错误！请问这是什么原因？

**Comment by underTheDark** [comment]
3.7版本的 用(resolve) => require([`@/views/${view}`], resolve)这种懒加载路由可以， () => import(`@/views/${view}`)这种懒加载不行。综合是什么原因造成的呢？

**Comment by yangzongzhuan** [comment]
参考类似的问题 https://gitee.com/y_project/RuoYi-Vue/issues/I4PZJF
