### ISSUE TITLE
tag-view点击查询问题

### ISSUE THREAD

**Issue by yeylong** [yangzongzhuan/RuoYi#104]
<img width="325" alt="微信截图_20211223111230" src="https://user-images.githubusercontent.com/96558333/147182481-8fed1d21-b22e-43db-bd2a-95e44a9b762e.png">
点击上方元数据管理功能的话，页面除了第一次查询时会刷新，后续就不会刷新了
但是点击其他两个功能模块，每次点击都会重新刷新，这是为什么啊？

**Comment by yangzongzhuan** [comment]
参考文档 http://doc.ruoyi.vip/ruoyi-vue/document/qdsc.html#页签缓存
