### ISSUE TITLE
请问，新增了公告，那么注册用户如何看到公告？

### ISSUE THREAD

**Issue by sky861421718163** [yangzongzhuan/RuoYi#105]
请问，管理员新增了公告，那么注册用户如何看到公告？
是需要给注册用户分配 查看公告的菜单权限吗？用户如何看到公告详情呢？因为没有查看详情的按钮，只有编辑时，才能看到公告的详情。麻烦解答下

**Comment by yangzongzhuan** [comment]
公告一般是自己在首页里面添加内容显示。这个需要自己去实现~因为不是都需要
