### ISSUE TITLE
登錄上去出现乱码问题

### ISSUE THREAD

**Issue by 0yingteam** [yangzongzhuan/RuoYi#107]
![图片](https://user-images.githubusercontent.com/61936554/150684858-12a3e092-d512-4193-bafb-111a6f644e20.png)
如上图，登录后出现乱码

**Comment by yangzongzhuan** [comment]
如果你没有新增其他的css导致样式被污染，那一般是数据库编码问题导致，你可以更换成utf8mb4或数据库脚本头部添加SET NAMES 'utf8';试试
