### ISSUE TITLE
input的type为number时无法使用backspace删除输入内容

### ISSUE THREAD

**Issue by ldg0529** [yangzongzhuan/RuoYi#111]
<input type="number"
类似以上这种无法使用backspace删除，只能选中用del删除，但是我用txt文本自己写了一个html是可以的，是有做了什么特殊处理吗？
使用的是chrome

**Comment by yangzongzhuan** [comment]
相同的问题 https://gitee.com/y_project/RuoYi/issues/I4XQCT
