### ISSUE TITLE
分页性能问题

### ISSUE THREAD

**Issue by feng88724** [yangzongzhuan/RuoYi#114]
```
@PostMapping("/list")
@ResponseBody
public TableDataInfo list(User user)
{
    startPage();  // 此方法配合前端完成自动分页
    List<User> list = userService.selectUserList(user);
    return getDataTable(list);
}
```

若依这种分页方式，如果数据量较大，是不是会有性能问题？

**Comment by aim467** [comment]
> ```
> @PostMapping("/list")
> @ResponseBody
> public TableDataInfo list(User user)
> {
>     startPage();  // 此方法配合前端完成自动分页
>     List<User> list = userService.selectUserList(user);
>     return getDataTable(list);
> }
> ```
> 
> 若依这种分页方式，如果数据量较大，是不是会有性能问题？

你看看 `startPage()` 方法，是不是使用 `PageHelper` 做了分页操作

**Comment by yangzongzhuan** [comment]
请在 https://gitee.com/y_project/RuoYi 里提问
