### ISSUE TITLE
微服务-服务网关-配置熔断降级，项目启动报错

### ISSUE THREAD

**Issue by zhuhuayun** [yangzongzhuan/RuoYi#115]
若依版本：3.4.0
按照：http://doc.ruoyi.vip/ruoyi-cloud/cloud/gateway.html#%E7%86%94%E6%96%AD%E9%99%8D%E7%BA%A7
操作截图如下：
![image](https://user-images.githubusercontent.com/86338852/165765639-d9c0ae21-b105-4d9f-9619-2f8f715c98be.png)
![image](https://user-images.githubusercontent.com/86338852/165765698-6349d077-003a-4f23-888d-31a00e0339cd.png)
![image](https://user-images.githubusercontent.com/86338852/165765941-5ebbd83e-e40d-491b-a6e1-30141a4d9b10.png)
![image](https://user-images.githubusercontent.com/86338852/165767412-7520e71e-8e31-4332-a3e3-fc1f25f055c0.png)
遇到问题一：引入依赖包，引入不了？
本人只好加了版本。
![image](https://user-images.githubusercontent.com/86338852/165768035-58e3b2d6-2651-4a9e-9783-69b87364a3da.png)
遇到问题二：
项目启动报错：java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;？
本人只好排除了低版本guava-15.0的依赖包。
![image](https://user-images.githubusercontent.com/86338852/165768127-df199f37-b230-4ea5-8e9e-fb1d122a1c57.png)
遇到问题三：
项目启动报错：java.lang.IllegalArgumentException: Unable to find GatewayFilterFactory with name Hystrix？
本人只好排除高版本spring-cloud-gateway-server-3.1.1的依赖包，引入低版本spring-cloud-gateway-server-2.2.6.RELEASE的依赖包。
![image](https://user-images.githubusercontent.com/86338852/165768233-a21573e4-acbc-4cfa-8a5e-8605d70eff9b.png)
遇到问题四：
项目启动报错：java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.gateway.config.GatewayAutoConfiguration.propertiesRouteDefinitionLocator
![image](https://user-images.githubusercontent.com/86338852/165768359-0c5ac715-2293-4e2f-a1e4-f0d701275008.png)
请求帮忙看看，谢谢！！！

**Comment by yangzongzhuan** [comment]
微服务版本请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues
