### ISSUE TITLE
ruoyi.scss 的某些样式会导致element ui的组件出现bug

### ISSUE THREAD

**Issue by Romio-L** [yangzongzhuan/RuoYi#120]
![image](https://user-images.githubusercontent.com/104606059/169728371-f6b33038-b446-46b0-bbf1-82ae0786ecf5.png)

会导致 Notification 在 right， left布局的时候出现 670px的最小高度

![image](https://user-images.githubusercontent.com/104606059/169728566-3ea28864-e07a-4e63-ab71-2d85954d7ead.png)
这个样式会导致 Notification  的标题文本出现偏高

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
