### ISSUE TITLE
一个关于请求问题

### ISSUE THREAD

**Issue by dsqlzh** [yangzongzhuan/RuoYi#124]
请求方式：axios，get
服务端：若依-服务版
nacos：已经对于该url设定了白名单
问题描述：发起两次请求，第二次的请求结果是404。
已知：两次请求都已经请求到了服务端，第二次请求失败了，没有异常log。
期望：能给给予帮助，或者给予一些猜测。
补充：两次请求，无论是间隔多久，发起第二次的时候404.

**Comment by yangzongzhuan** [comment]
微服务版本请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues
