### ISSUE TITLE
bootstrap-table 表头设置组合表头时，必现的bug

### ISSUE THREAD

**Issue by zhangchengting** [yangzongzhuan/RuoYi#125]
bootstrap-table 表头设置组合表头时，带check复选框， 勾选一行  selectFirstColumns 方法里面选取首行就的下标就不是1 了 table.options.columns[1].field  就会出错，导致下列代码块失效，永远不能启用

>  // 非多个禁用
>                     $('#' + toolbar + ' .multiple').toggleClass('disabled', !rows.length);
>                     // 非单个禁用
>                     $('#' + toolbar + ' .single').toggleClass('disabled', rows.length!=1);

**Comment by yangzongzhuan** [comment]
请在 https://gitee.com/y_project/RuoYi/issues 里提问
