### ISSUE TITLE
多图片左右点击轮播列表里怎么搞

### ISSUE THREAD

**Issue by yangfan2130** [yangzongzhuan/RuoYi#130]
多图片左右点击轮播列表里怎么搞

**Comment by yangfan2130** [comment]
![1656310302(1)](https://user-images.githubusercontent.com/74704234/175871448-fc3c0e50-bd31-4e85-9907-dc76352e6b8a.png)

**Comment by yangzongzhuan** [comment]
请在 https://gitee.com/y_project/RuoYi/issues 里提问
