### ISSUE TITLE
若依前vue后端分离版本，前端问题

### ISSUE THREAD

**Issue by 404area** [yangzongzhuan/RuoYi#132]
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/50036307/176608055-e60706b2-c94a-4efc-8a9f-777c34a7b9fb.png">

前端弹窗显示有问题，显示不全未换行

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
