### ISSUE TITLE
定时任务使用，ry跑不起来

### ISSUE THREAD

**Issue by secanter** [yangzongzhuan/RuoYi#133]
[](![AVIX(DSB292QHR_AYH0YGRP](https://user-images.githubusercontent.com/74842831/176733762-a99837b0-643a-4772-9036-8e0e912061ed.png))
`E:\workspace\java\jdk\bin\java.exe -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true "-javaagent:E:\workspace\ij\IntelliJ IDEA 2021.3.3\lib\idea_rt.jar=3489:E:\workspace\ij\IntelliJ IDEA 2021.3.3\bin" -Dfile.encoding=UTF-8 -classpath E:\workspace\java\jdk\jre\lib\charsets.jar;E:\workspace\java\jdk\jre\lib\deploy.jar;E:\workspace\java\jdk\jre\lib\ext\access-bridge-64.jar;E:\workspace\java\jdk\jre\lib\ext\cldrdata.jar;E:\workspace\java\jdk\jre\lib\ext\dnsns.jar;E:\workspace\java\jdk\jre\lib\ext\jaccess.jar;E:\workspace\java\jdk\jre\lib\ext\jfxrt.jar;E:\workspace\java\jdk\jre\lib\ext\localedata.jar;E:\workspace\java\jdk\jre\lib\ext\nashorn.jar;E:\workspace\java\jdk\jre\lib\ext\sunec.jar;E:\workspace\java\jdk\jre\lib\ext\sunjce_provider.jar;E:\workspace\java\jdk\jre\lib\ext\sunmscapi.jar;E:\workspace\java\jdk\jre\lib\ext\sunpkcs11.jar;E:\workspace\java\jdk\jre\lib\ext\zipfs.jar;E:\workspace\java\jdk\jre\lib\javaws.jar;E:\workspace\java\jdk\jre\lib\jce.jar;E:\workspace\java\jdk\jre\lib\jfr.jar;E:\workspace\java\jdk\jre\lib\jfxswt.jar;E:\workspace\java\jdk\jre\lib\jsse.jar;E:\workspace\java\jdk\jre\lib\management-agent.jar;E:\workspace\java\jdk\jre\lib\plugin.jar;E:\workspace\java\jdk\jre\lib\resources.jar;E:\workspace\java\jdk\jre\lib\rt.jar;E:\workspace\software_cup\test0621\omniscience\target\classes;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot-starter\2.1.18.RELEASE\spring-boot-starter-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot\2.1.18.RELEASE\spring-boot-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot-autoconfigure\2.1.18.RELEASE\spring-boot-autoconfigure-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot-starter-logging\2.1.18.RELEASE\spring-boot-starter-logging-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;C:\Users\secanter\.m2\repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;C:\Users\secanter\.m2\repository\org\apache\logging\log4j\log4j-to-slf4j\2.11.2\log4j-to-slf4j-2.11.2.jar;C:\Users\secanter\.m2\repository\org\apache\logging\log4j\log4j-api\2.11.2\log4j-api-2.11.2.jar;C:\Users\secanter\.m2\repository\org\slf4j\jul-to-slf4j\1.7.30\jul-to-slf4j-1.7.30.jar;C:\Users\secanter\.m2\repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-core\5.1.19.RELEASE\spring-core-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-jcl\5.1.19.RELEASE\spring-jcl-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\yaml\snakeyaml\1.23\snakeyaml-1.23.jar;C:\Users\secanter\.m2\repository\net\bytebuddy\byte-buddy\1.9.16\byte-buddy-1.9.16.jar;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot-starter-aop\2.1.18.RELEASE\spring-boot-starter-aop-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-aop\5.1.19.RELEASE\spring-aop-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\aspectj\aspectjweaver\1.9.6\aspectjweaver-1.9.6.jar;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot-starter-web\2.1.18.RELEASE\spring-boot-starter-web-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot-starter-json\2.1.18.RELEASE\spring-boot-starter-json-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.9.10\jackson-datatype-jdk8-2.9.10.jar;C:\Users\secanter\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.9.10\jackson-datatype-jsr310-2.9.10.jar;C:\Users\secanter\.m2\repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.9.10\jackson-module-parameter-names-2.9.10.jar;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot-starter-tomcat\2.1.18.RELEASE\spring-boot-starter-tomcat-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\org\apache\tomcat\embed\tomcat-embed-core\9.0.39\tomcat-embed-core-9.0.39.jar;C:\Users\secanter\.m2\repository\org\apache\tomcat\embed\tomcat-embed-el\9.0.39\tomcat-embed-el-9.0.39.jar;C:\Users\secanter\.m2\repository\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.39\tomcat-embed-websocket-9.0.39.jar;C:\Users\secanter\.m2\repository\org\hibernate\validator\hibernate-validator\6.0.21.Final\hibernate-validator-6.0.21.Final.jar;C:\Users\secanter\.m2\repository\javax\validation\validation-api\2.0.1.Final\validation-api-2.0.1.Final.jar;C:\Users\secanter\.m2\repository\org\jboss\logging\jboss-logging\3.3.3.Final\jboss-logging-3.3.3.Final.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-web\5.1.19.RELEASE\spring-web-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-webmvc\5.1.19.RELEASE\spring-webmvc-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-expression\5.1.19.RELEASE\spring-expression-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot-starter-thymeleaf\2.1.18.RELEASE\spring-boot-starter-thymeleaf-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\org\thymeleaf\thymeleaf-spring5\3.0.11.RELEASE\thymeleaf-spring5-3.0.11.RELEASE.jar;C:\Users\secanter\.m2\repository\org\thymeleaf\thymeleaf\3.0.11.RELEASE\thymeleaf-3.0.11.RELEASE.jar;C:\Users\secanter\.m2\repository\org\attoparser\attoparser\2.0.5.RELEASE\attoparser-2.0.5.RELEASE.jar;C:\Users\secanter\.m2\repository\org\unbescape\unbescape\1.1.6.RELEASE\unbescape-1.1.6.RELEASE.jar;C:\Users\secanter\.m2\repository\org\thymeleaf\extras\thymeleaf-extras-java8time\3.0.4.RELEASE\thymeleaf-extras-java8time-3.0.4.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot-devtools\2.1.18.RELEASE\spring-boot-devtools-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\mysql\mysql-connector-java\8.0.22\mysql-connector-java-8.0.22.jar;C:\Users\secanter\.m2\repository\org\mybatis\spring\boot\mybatis-spring-boot-starter\2.1.3\mybatis-spring-boot-starter-2.1.3.jar;C:\Users\secanter\.m2\repository\org\springframework\boot\spring-boot-starter-jdbc\2.1.18.RELEASE\spring-boot-starter-jdbc-2.1.18.RELEASE.jar;C:\Users\secanter\.m2\repository\com\zaxxer\HikariCP\3.2.0\HikariCP-3.2.0.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-jdbc\5.1.19.RELEASE\spring-jdbc-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-tx\5.1.19.RELEASE\spring-tx-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\mybatis\spring\boot\mybatis-spring-boot-autoconfigure\2.1.3\mybatis-spring-boot-autoconfigure-2.1.3.jar;C:\Users\secanter\.m2\repository\org\mybatis\mybatis\3.5.5\mybatis-3.5.5.jar;C:\Users\secanter\.m2\repository\org\mybatis\mybatis-spring\2.0.5\mybatis-spring-2.0.5.jar;C:\Users\secanter\.m2\repository\com\github\pagehelper\pagehelper-spring-boot-starter\1.3.0\pagehelper-spring-boot-starter-1.3.0.jar;C:\Users\secanter\.m2\repository\com\github\pagehelper\pagehelper-spring-boot-autoconfigure\1.3.0\pagehelper-spring-boot-autoconfigure-1.3.0.jar;C:\Users\secanter\.m2\repository\com\github\pagehelper\pagehelper\5.2.0\pagehelper-5.2.0.jar;C:\Users\secanter\.m2\repository\com\github\jsqlparser\jsqlparser\3.2\jsqlparser-3.2.jar;C:\Users\secanter\.m2\repository\com\alibaba\druid-spring-boot-starter\1.2.2\druid-spring-boot-starter-1.2.2.jar;C:\Users\secanter\.m2\repository\com\alibaba\druid\1.2.2\druid-1.2.2.jar;C:\Users\secanter\.m2\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;C:\Users\secanter\.m2\repository\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;C:\Users\secanter\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\secanter\.m2\repository\commons-fileupload\commons-fileupload\1.3.3\commons-fileupload-1.3.3.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-core\1.7.0\shiro-core-1.7.0.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-lang\1.7.0\shiro-lang-1.7.0.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-cache\1.7.0\shiro-cache-1.7.0.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-crypto-hash\1.7.0\shiro-crypto-hash-1.7.0.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-crypto-core\1.7.0\shiro-crypto-core-1.7.0.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-crypto-cipher\1.7.0\shiro-crypto-cipher-1.7.0.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-config-core\1.7.0\shiro-config-core-1.7.0.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-config-ogdl\1.7.0\shiro-config-ogdl-1.7.0.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-event\1.7.0\shiro-event-1.7.0.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-spring\1.7.0\shiro-spring-1.7.0.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-web\1.7.0\shiro-web-1.7.0.jar;C:\Users\secanter\.m2\repository\org\owasp\encoder\encoder\1.2.2\encoder-1.2.2.jar;C:\Users\secanter\.m2\repository\org\apache\shiro\shiro-ehcache\1.7.0\shiro-ehcache-1.7.0.jar;C:\Users\secanter\.m2\repository\net\sf\ehcache\ehcache-core\2.6.11\ehcache-core-2.6.11.jar;C:\Users\secanter\.m2\repository\com\github\theborakompanioni\thymeleaf-extras-shiro\2.0.0\thymeleaf-extras-shiro-2.0.0.jar;C:\Users\secanter\.m2\repository\com\alibaba\fastjson\1.2.74\fastjson-1.2.74.jar;C:\Users\secanter\.m2\repository\eu\bitwalker\UserAgentUtils\1.21\UserAgentUtils-1.21.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-context-support\5.1.19.RELEASE\spring-context-support-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-beans\5.1.19.RELEASE\spring-beans-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\spring-context\5.1.19.RELEASE\spring-context-5.1.19.RELEASE.jar;C:\Users\secanter\.m2\repository\org\quartz-scheduler\quartz\2.3.2\quartz-2.3.2.jar;C:\Users\secanter\.m2\repository\com\mchange\mchange-commons-java\0.2.15\mchange-commons-java-0.2.15.jar;C:\Users\secanter\.m2\repository\org\apache\velocity\velocity\1.7\velocity-1.7.jar;C:\Users\secanter\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\secanter\.m2\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar;C:\Users\secanter\.m2\repository\com\github\penggle\kaptcha\2.3.2\kaptcha-2.3.2.jar;C:\Users\secanter\.m2\repository\com\jhlabs\filters\2.0.235-1\filters-2.0.235-1.jar;C:\Users\secanter\.m2\repository\io\springfox\springfox-swagger2\2.9.2\springfox-swagger2-2.9.2.jar;C:\Users\secanter\.m2\repository\io\springfox\springfox-spi\2.9.2\springfox-spi-2.9.2.jar;C:\Users\secanter\.m2\repository\io\springfox\springfox-core\2.9.2\springfox-core-2.9.2.jar;C:\Users\secanter\.m2\repository\io\springfox\springfox-schema\2.9.2\springfox-schema-2.9.2.jar;C:\Users\secanter\.m2\repository\io\springfox\springfox-swagger-common\2.9.2\springfox-swagger-common-2.9.2.jar;C:\Users\secanter\.m2\repository\io\springfox\springfox-spring-web\2.9.2\springfox-spring-web-2.9.2.jar;C:\Users\secanter\.m2\repository\com\google\guava\guava\20.0\guava-20.0.jar;C:\Users\secanter\.m2\repository\com\fasterxml\classmate\1.4.0\classmate-1.4.0.jar;C:\Users\secanter\.m2\repository\org\springframework\plugin\spring-plugin-core\1.2.0.RELEASE\spring-plugin-core-1.2.0.RELEASE.jar;C:\Users\secanter\.m2\repository\org\springframework\plugin\spring-plugin-metadata\1.2.0.RELEASE\spring-plugin-metadata-1.2.0.RELEASE.jar;C:\Users\secanter\.m2\repository\org\mapstruct\mapstruct\1.2.0.Final\mapstruct-1.2.0.Final.jar;C:\Users\secanter\.m2\repository\io\swagger\swagger-annotations\1.5.21\swagger-annotations-1.5.21.jar;C:\Users\secanter\.m2\repository\io\swagger\swagger-models\1.5.21\swagger-models-1.5.21.jar;C:\Users\secanter\.m2\repository\io\springfox\springfox-swagger-ui\2.9.2\springfox-swagger-ui-2.9.2.jar;C:\Users\secanter\.m2\repository\com\github\oshi\oshi-core\5.3.6\oshi-core-5.3.6.jar;C:\Users\secanter\.m2\repository\net\java\dev\jna\jna\5.6.0\jna-5.6.0.jar;C:\Users\secanter\.m2\repository\net\java\dev\jna\jna-platform\5.6.0\jna-platform-5.6.0.jar;C:\Users\secanter\.m2\repository\org\apache\poi\poi-ooxml\4.1.2\poi-ooxml-4.1.2.jar;C:\Users\secanter\.m2\repository\org\apache\poi\poi\4.1.2\poi-4.1.2.jar;C:\Users\secanter\.m2\repository\commons-codec\commons-codec\1.11\commons-codec-1.11.jar;C:\Users\secanter\.m2\repository\org\apache\commons\commons-math3\3.6.1\commons-math3-3.6.1.jar;C:\Users\secanter\.m2\repository\com\zaxxer\SparseBitSet\1.2\SparseBitSet-1.2.jar;C:\Users\secanter\.m2\repository\org\apache\poi\poi-ooxml-schemas\4.1.2\poi-ooxml-schemas-4.1.2.jar;C:\Users\secanter\.m2\repository\org\apache\xmlbeans\xmlbeans\3.1.0\xmlbeans-3.1.0.jar;C:\Users\secanter\.m2\repository\org\apache\commons\commons-compress\1.19\commons-compress-1.19.jar;C:\Users\secanter\.m2\repository\com\github\virtuald\curvesapi\1.06\curvesapi-1.06.jar;C:\Users\secanter\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.12.3\jackson-databind-2.12.3.jar;C:\Users\secanter\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.12.3\jackson-annotations-2.12.3.jar;C:\Users\secanter\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.12.3\jackson-core-2.12.3.jar;C:\Users\secanter\.m2\repository\com\hankcs\hanlp\portable-1.7.5\hanlp-portable-1.7.5.jar;C:\Users\secanter\.m2\repository\com\opencsv\opencsv\5.4\opencsv-5.4.jar;C:\Users\secanter\.m2\repository\org\apache\commons\commons-text\1.9\commons-text-1.9.jar;C:\Users\secanter\.m2\repository\commons-beanutils\commons-beanutils\1.9.4\commons-beanutils-1.9.4.jar;C:\Users\secanter\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\secanter\.m2\repository\org\apache\commons\commons-collections4\4.4\commons-collections4-4.4.jar;E:\workspace\software_cup\test0621\omniscience\lib\lombok.jar;E:\workspace\software_cup\test0621\omniscience\lib\ecloud-sdk-nlp-2.0.1-jar-with-dependencies.jar;E:\workspace\software_cup\test0621\omniscience\lib\ecloud-sdk-ocr-1.5.3-jar-with-dependencies.jar com.ruoyi.RuoYiApplication
Application Version: 4.5.1
Spring Boot Version: 2.1.18.RELEASE
////////////////////////////////////////////////////////////////////
//                          _ooOoo_                               //
//                         o8888888o                              //
//                         88" . "88                              //
//                         (| ^_^ |)                              //
//                         O\  =  /O                              //
//                      ____/`---'\____                           //
//                    .'  \\|     |//  `.                         //
//                   /  \\|||  :  |||//  \                        //
//                  /  _||||| -:- |||||-  \                       //
//                  |   | \\\  -  /// |   |                       //
//                  | \_|  ''\---/''  |   |                       //
//                  \  .-\__  `-`  ___/-. /                       //
//                ___`. .'  /--.--\  `. . ___                     //
//              ."" '<  `.___\_<|>_/___.'  >'"".                  //
//            | | :  `- \`.;`\ _ /`;.`/ - ` : | |                 //
//            \  \ `-.   \_ __\ /__ _/   .-` /  /                 //
//      ========`-.____`-.___\_____/___.-`____.-'========         //
//                           `=---='                              //
//      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        //
//            佛祖保佑       永不宕机     永无BUG                 //
////////////////////////////////////////////////////////////////////
00:34:57.309 [restartedMain] INFO  c.r.RuoYiApplication - [logStarting,50] - Starting RuoYiApplication on DESKTOP-ODH8K6S with PID 1312 (E:\workspace\software_cup\test0621\omniscience\target\classes started by secanter in E:\workspace\software_cup\test0621\omniscience)
00:34:57.311 [restartedMain] DEBUG c.r.RuoYiApplication - [logStarting,53] - Running with Spring Boot v2.1.18.RELEASE, Spring v5.1.19.RELEASE
00:34:57.311 [restartedMain] INFO  c.r.RuoYiApplication - [logStartupProfileInfo,652] - The following profiles are active: druid
00:34:57.699 [restartedMain] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - [refresh,558] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.ruoyi.RuoYiApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'ryTask' for bean class [com.ruoyi.project.system.news_tool.RyTask] conflicts with existing, non-compatible bean definition of same name and class [com.ruoyi.project.monitor.job.task.RyTask]
00:34:57.708 [restartedMain] ERROR o.s.b.SpringApplication - [reportFailure,823] - Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.ruoyi.RuoYiApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'ryTask' for bean class [com.ruoyi.project.system.news_tool.RyTask] conflicts with existing, non-compatible bean definition of same name and class [com.ruoyi.project.monitor.job.task.RyTask]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:182)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.ruoyi.RuoYiApplication.main(RuoYiApplication.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'ryTask' for bean class [com.ruoyi.project.system.news_tool.RyTask] conflicts with existing, non-compatible bean definition of same name and class [com.ruoyi.project.monitor.job.task.RyTask]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:348)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:286)
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:132)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:288)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:243)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:200)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:168)
	... 18 common frames omitted

Process finished with exit code 0
`

**Comment by yangzongzhuan** [comment]
请在 https://gitee.com/y_project/RuoYi/issues 里提问
