### ISSUE TITLE
关于该项目中部分方法命名的建议

### ISSUE THREAD

**Issue by HughTang** [yangzongzhuan/RuoYi#136]
尊敬的开发者RuoYi：
        您好！非常感谢您能抽出宝贵的时间来阅读此Issue，我们是来自西北工业大学软件学院硕士课题组的科研团队，正在进行一项关于Java开源项目中方法（函数）名称一致性检查和建议的科研研究，方法（函数）名称的可读性对开发人员理解代码至关重要，我们将您在GitHub中发布的RuoYi开源项目作为了我们研发工具DMName的实验验证对象，我们发现您的项目中存在的方法（函数）命名问题主要是在命名时缺乏get动词前缀，文件链接（举例）：https://github.com/yangzongzhuan/RuoYi/blob/master/ruoyi-admin/src/main/java/com/ruoyi/web/controller/demo/controller/DemoFormController.java

第42行原方法名称为button，推荐方法名称改为getButton
第51行原方法名称为select，推荐方法名称改为getSelect
第60行原方法名称为timeline，推荐方法名称改为getTimeline
第105行原方法名称为labels_tips，推荐方法名称改为getLabelsTips
第114行原方法名称为tabs_panels，推荐方法名称改为getTabsPanels
第123行原方法名称为grid，推荐方法名称改为getGrid
第132行原方法名称为wizard，推荐方法名称改为getWizard
第150行原方法名称为datetime，推荐方法名称改为getDateTime
第159行原方法名称为duallistbox，推荐方法名称改为getDualListBox
第168行原方法名称为basic，推荐方法名称改为getBasic
第177行原方法名称为cards，推荐方法名称改为getCards
第186行原方法名称为summernote，推荐方法名称改为getSummerNote
第204行原方法名称为cxselect，推荐方法名称改为getCxSelect
第246行原方法名称为localRefresh，推荐方法名称改为getLocalRefresh
第267行原方法名称为localRefreshTask，推荐方法名称改为getLocalRefreshTask
第289行原方法名称为cityData，推荐方法名称改为getCityData
第300行原方法名称为userModel，推荐方法名称改为getUserModel
第314行原方法名称为collection，推荐方法名称改为getCollection
第行原方法名称为，推荐方法名称改为
        如果您认可或反对上述所涉及的问题和命名建议，可以发邮件（[hughtang@mail.nwpu.edu.cn](mailto:hughtang@mail.nwpu.edu.cn)）联系我们或直接在本Issue下回复，我们由衷地希望能够得到您宝贵的意见反馈，期待您的回复！

**Comment by yangzongzhuan** [comment]
这个类都是提供的示例代码，为了方便识别就简单命名了，修改的意义不大。
