### ISSUE TITLE
建议用lombok替代getter setter

### ISSUE THREAD

**Issue by jack999527** [yangzongzhuan/RuoYi#146]

**Comment by zhangmrit** [comment]
有mp的扩展版本，同时支持了lombok和mp，甚至其他插件，你可以到扩展专区寻找


| |
张孟如
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月28日 08:54 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [yangzongzhuan/RuoYi] 建议用lombok替代getter setter (Issue #146) |

**Comment by yangzongzhuan** [comment]
不考虑lombok，有需要可以自己去集成。
