### ISSUE TITLE
建议任务执行工具中添加InheritableThreadLocal常量用户可自行保存执行的自定义结果，并放入调度日志

### ISSUE THREAD

**Issue by kennimade** [yangzongzhuan/RuoYi#148]

**Comment by yangzongzhuan** [comment]
不太明白你的意思，你可以PR上来看一下。
https://gitee.com/y_project/RuoYi/pulls
如果被合并会成为一名贡献者出现在列表中 https://gitee.com/y_project/RuoYi/contributors?ref=master
