### ISSUE TITLE
关于多数据源的坑

### ISSUE THREAD

**Issue by JADE-Jerry** [yangzongzhuan/RuoYi#15]
在开发过程中发现，即使配置了使用多数据源，但是依然报错。日志打印切换了数据源，但实际还是用的原数据源。最后发现是方法注释了@Transaction导致了出错。最终将事务注释去掉就没问题了。
举例：
A()，注释使用数据源Slave。
B() { A() }，注释了@Transaction。最终导致内部的A还是用了数据源Master，没用Slave。将B方法上的事务去掉就OK了。
======================================================
希望在多数据源的文档里说明这种情况，避免其他兄弟踩坑。

**Comment by yangzongzhuan** [comment]
嗯，多数据源不支持事务操作。
