### ISSUE TITLE
想用RuoYi-vue控制小程序版本的不同角色查看不同菜单如何实现呢？

### ISSUE THREAD

**Issue by Vvvcat** [yangzongzhuan/RuoYi#152]

**Comment by Vvvcat** [comment]
很急，求求求求

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues

**Comment by ChengJun24** [comment]
登录成功后会把所有菜单的权限通过getRouter接口返给前端，里面有详细的是否显示隐藏的字段的，直接前端页面做适配。
