### ISSUE TITLE
请问如何批量修改表中的数据

### ISSUE THREAD

**Issue by luoxinqy** [yangzongzhuan/RuoYi#156]

**Comment by yangzongzhuan** [comment]
参考代码生成的修改。

**Comment by ChengJun24** [comment]
update table set a = 1，后面不跟条件就是批量修改的啊。

**Comment by ChengJun24** [comment]
1、 replace into 批量更新
replace into 表名l (id,字段1) values (1,'2'),(2,'3'),...(x,'y');
2、insert into ...on duplicate key update批量更新
insert into 表名l (id,字段1) values (1,'2'),(2,'3'),...(x,'y') on duplicate key update 字段1=values(字段1);
