### ISSUE TITLE
关于冻结列的问题

### ISSUE THREAD

**Issue by lucky-zeng** [yangzongzhuan/RuoYi#16]
设置了冻结列。列表上重复两个列的问题。如图：
![image](https://user-images.githubusercontent.com/58682449/79943982-fe092c00-849c-11ea-85d0-fb245756b883.png)

![image](https://user-images.githubusercontent.com/58682449/79944051-314bbb00-849d-11ea-89d1-c35bfa3fd201.png)

**Comment by yangzongzhuan** [comment]
列较多的情况下目前还不能自适应，可以手动在当前页面调整下右侧距离和宽度。

```
.right-fixed-table-columns{ 
    right:38px!important;
    width:20px!important;
}
```
