### ISSUE TITLE
更新用户信息时，如果对象值为null则无法更新

### ISSUE THREAD

**Issue by jbasttdi** [yangzongzhuan/RuoYi#161]
现在的代码都是
`<if test="xxx != null and xxx != ''">`
这样的方式，
如果需要保存前端传过来的email空值则无法进行更新。
`
<update id="updateUser" parameterType="SysUser">`
` 		update sys_user`
` 		<set>`
` 			<if test="email != null and email != ''">email = #{email},</if>`
`....`
` 			<if test="remark != null">remark = #{remark},</if>`
 		`	update_time = sysdate()`
 		`</set>`
 	`	where user_id = #{userId}`
	`</update>`

**Comment by ChengJun24** [comment]
<if test="xxx != null and xxx != ''">这样写没毛病啊

**Comment by yangzongzhuan** [comment]
去 掉 `xxx != ''` 空串的判断
