### ISSUE TITLE
swagger报错

### ISSUE THREAD

**Issue by Asmallsoldier** [yangzongzhuan/RuoYi#166]
Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

**Comment by yangzongzhuan** [comment]
测试验证是有效的，没有你说的问题, 请提供出能复现问题详细描述和步骤。
