### ISSUE TITLE
系统模块（ruoyi-common）如何调用新创建模块的类方法？

### ISSUE THREAD

**Issue by lanyazhizhou** [yangzongzhuan/RuoYi#167]
如图所示，我在新模块中引入一个外部的jar包，然后调用其方法，现在有个需求要在common模块中调用该方法，但是发现在common模块中无法引入新模块。

目前的解决方案是，将该方法和外包jar包放入到common模块中，这样两个模块都可以访问该方法；不过，我想知道有没有其他更为简单的方法，比如能在common模块中引用新模块的方法。

**Comment by ChengJun24** [comment]
在common模块的pom文件里引入新模块的dependency

**Comment by yangzongzhuan** [comment]
外部jar都可以install到本地maven去依赖
