### ISSUE TITLE
swagger using IP access will cause /csrf 404

### ISSUE THREAD

**Issue by gaoyf95** [yangzongzhuan/RuoYi#17]
**From what I could figure out from the source code of swagger-ui it can work without those endpoints. Basically it uses the base url to search in the html for a csrf meta information or if that fails it checks an endpoint /csrf to check for csrf token. As last the cookies are checked if some contains the XSRF-TOKEN value**
### solution:
1. Shiroconfig file release permission
           `filterChainDefinitionMap.put("/swagger-ui.html", "anon");<br/>
            filterChainDefinitionMap.put("/swagger-resources/**", "anon");<br/>
            filterChainDefinitionMap.put("/v2/**", "anon");<br/>
            filterChainDefinitionMap.put("/webjars/**", "anon");` <br/>

2. Reduce swagger to 2.8.0
3. Add cross domain lifter
4. Modify the swagger configuration of ResourcesConfig
`registry.addResourceHandler("swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/swagger-ui.html");`

**Comment by yangzongzhuan** [comment]
你如果需要不登录的情况下访问swagger可以这么配置，但是一般不建议这么做。因为这样大家都能看到了。不安全。
