### ISSUE TITLE
表头处添加点击事件

### ISSUE THREAD

**Issue by hxl123789** [yangzongzhuan/RuoYi#172]
![image](https://user-images.githubusercontent.com/2535778/224551041-ffdb8980-390d-4c85-a734-770c217f04e2.png)
需要在表头处添加点击事件，再进行前端筛选，试了好几种方法都获利不了点击事件

**Comment by yangzongzhuan** [comment]
不分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi/issues
