### ISSUE TITLE
vue前端分离版，node_modules包为什么运行体积越来越大

### ISSUE THREAD

**Issue by tanhaoAli** [yangzongzhuan/RuoYi#173]
node_modules包体积有几十个G，每次运行都会增大体积，这是为什么呢

**Comment by yaunsine** [comment]
有重复下载，`npm clean`

> node_modules包体积有几十个G，每次运行都会增大体积，这是为什么呢

**Comment by yangzongzhuan** [comment]
用最新的版本 配置 cache: false
