### ISSUE TITLE
Get请求方式传递实体参数的问题

### ISSUE THREAD

**Issue by MiracleCatcher** [yangzongzhuan/RuoYi#181]
哥哥们问一下 微服务写远程Feign接口的时候 Get方式请求传实体参数
1.Feign接口和控制器都不加@RequestParam注解 会报这个Feign接口不支持Post请求
2.Feign接口和控制器都都加@RequestParam注解 会报String不能转换为实体
3.Feign接口加@RequestParam注解 控制器不加@RequestParam注解 不报错 但是传的实体属性都为空
这种情况下除了修改成Post请求外还有什么方式 即用Get请求又能传递实体参数

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues 需要提供出能复现问题详细步骤。
