### ISSUE TITLE
加入context-path之后超时登录URL多了一个端口号

### ISSUE THREAD

**Issue by TernenceZhou** [yangzongzhuan/RuoYi#182]
项目是前后端未分离的，uat环境接入网关之后，登录超时自动跳转URL的时候发现多带了一个端口号 大佬知道是什么原因吗
![企业微信截图_16826588327549](https://user-images.githubusercontent.com/30793535/235059993-970a5bc9-b99d-4833-a6da-a1ff2fbf293d.png)

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues 需要提供出能复现问题详细步骤。
