### ISSUE TITLE
Convert.digitUppercase方法，数字金额大写转换double类型失真问题

### ISSUE THREAD

**Issue by ghost5444** [yangzongzhuan/RuoYi#183]
for (int i = 0; i < fraction.length; i++)
  {
     s += (digit[(int) (Math.floor(n * 10 * Math.pow(10, i)) % 10)] + fraction[i]).replaceAll("(零.)+", "");
 }
double数据类型 n 在进行运算时，会造成失真问题。例如 67348.18 在转换后会变为 陆万柒仟叁佰肆拾捌元壹角柒分

**Comment by yangzongzhuan** [comment]
最新版已修复此问题。
