### ISSUE TITLE
首行固定下拉到最下面表格会出现错位

### ISSUE THREAD

**Issue by xiaozhuangc** [yangzongzhuan/RuoYi#184]
因为首行需要固定，页面下拉到最下面时就会出现错位的情况，只要窗口尺寸发生变更就会恢复正常，下面的滑块只要在页面最前面也不会出现。
![Uploading QQ截图20230518103734.png…]()

**Comment by xiaozhuangc** [comment]
![QQ截图20230518103734](https://github.com/yangzongzhuan/RuoYi/assets/68954057/5399d67b-53f5-40d7-8d3e-7602781d87dd)

**Comment by IGoodBoy6** [comment]
你这是表格限制了固定高么？

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
