### ISSUE TITLE
关于数据权限的使用，是否只能手写sql的情况下生效呢，如果是用mybatis-plus的Wrapper应该如何处理呢

### ISSUE THREAD

**Issue by ypcfly** [yangzongzhuan/RuoYi#185]
我看手册写的也是要自己在xml里面将param.datasope加到sql最后。但是使用mybatis-plus不手动写sql改怎么办呢

**Comment by yangzongzhuan** [comment]
参考项目扩展其他使用mybatis plus小伙伴的做法 http://doc.ruoyi.vip/ruoyi-vue/document/xmkz.html
