### ISSUE TITLE
关于远程调用疑问

### ISSUE THREAD

**Issue by jparameter** [yangzongzhuan/RuoYi#188]
实验了一下在两个不同的模块之间   A   B  如果A想使用B里的方法
在A的pom里引用B后
比如在A的controller  @Autowired  一下 B 的  mapper
就可以直接在A的方法里直接使用  B  mapper里的方法了而且是能取到数据的
那么远程调用的存在是为了什么，来自小白的疑问

**Comment by zhangmrit** [comment]
你现在是在同一环境，实际中，可能是不同的数据库，不同的包，A或许可以调用B的代码，但是数据是查不到的，远程调用的意思是，A和B可以完全分离


| |
张孟如
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月1日 16:15 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [yangzongzhuan/RuoYi] 关于远程调用疑问 (Issue #188) |

实验了一下在两个不同的模块之间 A B 如果A想使用B里的方法
在A的pom里引用B后
比如在A的controller @Autowired 一下 B 的 mapper
就可以直接在A的方法里直接使用 B mapper里的方法了而且是能取到数据的
那么远程调用的存在是为了什么，来自小白的疑问
