### ISSUE TITLE
我是一个前端，后端给了我一个上传文件接口，联调过程中出现现象如下图

### ISSUE THREAD

**Issue by huangwenboha563** [yangzongzhuan/RuoYi#191]
![dc7cc0b0f4df723bef16ad48497d29da](https://github.com/yangzongzhuan/RuoYi/assets/24206806/045560e1-aa8a-4d00-b28d-3a4a002caa4a)
![image](https://github.com/yangzongzhuan/RuoYi/assets/24206806/bfe0b472-31a8-4626-b980-73fc5a3a4f5b)

**Comment by yangzongzhuan** [comment]
这个错误只能你们双方去检查了，因为是你们自己写的业务逻辑，非通用方法，一般是后台限制了，
