### ISSUE TITLE
jimureport 集成到ruoyi master 版 maven冲突?

### ISSUE THREAD

**Issue by apachexc** [yangzongzhuan/RuoYi#192]
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.ruoyi.framework.config.properties.DruidProperties.dataSource(DruidProperties.java:65)

The following method did not exist:

    com.alibaba.druid.pool.DruidDataSource.setConnectTimeout(I)V

The method's class, com.alibaba.druid.pool.DruidDataSource, is available from the following locations:

    jar:file:/D:/Program%20Files/apache-maven-3.6.1/repository/com/alibaba/druid/1.1.22/druid-1.1.22.jar!/com/alibaba/druid/pool/DruidDataSource.class

The class hierarchy was loaded from the following locations:

    com.alibaba.druid.pool.DruidDataSource: file:/D:/Program%20Files/apache-maven-3.6.1/repository/com/alibaba/druid/1.1.22/druid-1.1.22.jar
    com.alibaba.druid.pool.DruidAbstractDataSource: file:/D:/Program%20Files/apache-maven-3.6.1/repository/com/alibaba/druid/1.1.22/druid-1.1.22.jar
    com.alibaba.druid.pool.WrapperAdapter: file:/D:/Program%20Files/apache-maven-3.6.1/repository/com/alibaba/druid/1.1.22/druid-1.1.22.jar

**Comment by apachexc** [comment]
![AA 604A24DD9AC(FV$JFD1M](https://github.com/yangzongzhuan/RuoYi/assets/19464129/a29ede85-e85e-485c-8d23-ba65a4236da1)

**Comment by yangzongzhuan** [comment]
那你只能降低druid版本了，因为旧版没有超时的方法。
