### ISSUE TITLE
BUG 应该先更新数据库，再删除缓存

### ISSUE THREAD

**Issue by thetbw** [yangzongzhuan/RuoYi#193]
参考文件 73行  https://github.com/yangzongzhuan/RuoYi/blob/master/ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/SysMenuController.java

相关代码还存在于 SysRoleController

先删除缓存后更新数据库导致数据没有生效

**Comment by yangzongzhuan** [comment]
这个没有任何的影响，缓存没了点击也会重新加载。
