### ISSUE TITLE
自建时间字段，查询返回值和出createTime一样在查询后转换时间多了12个小时

### ISSUE THREAD

**Issue by robothe** [yangzongzhuan/RuoYi#194]
<img width="312" alt="截屏2023-07-17 21 21 17" src="https://github.com/yangzongzhuan/RuoYi/assets/139799468/622e33c6-d250-4f9a-9055-406516e506db">
<img width="486" alt="截屏2023-07-17 21 20 35" src="https://github.com/yangzongzhuan/RuoYi/assets/139799468/e6dfde43-de36-4dab-865b-c7a81d3d2200">
<img width="425" alt="截屏2023-07-17 21 19 32" src="https://github.com/yangzongzhuan/RuoYi/assets/139799468/3831e450-4153-4885-95b4-13ee88170720">

**Comment by yangzongzhuan** [comment]
不分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi/issues 需要提供出能复现问题详细步骤。
