### ISSUE TITLE
返回值通过stream collect处理后分页功能存在异常

### ISSUE THREAD

**Issue by lixuankun** [yangzongzhuan/RuoYi#198]
List<SysUser> sysUsers = userMapper.selectUserList(user);
for (SysUser u : sysUsers) {
  u.setCanBeWrite(1);
}
return sysUsers;
这样返回正常
return userMapper.selectUserList(user).stream().peek(u -> {
              u.setCanBeWrite(1);
 }).collect(Collectors.toList());
这样分页返回只有一页了

**Comment by yangzongzhuan** [comment]
pagehelper 的问题，建议将stream换成其他方式。
