### ISSUE TITLE
首页重复使用thymeleaf内联方式[[]]直接获取系统默认主题，未能体现浏览器缓存判断

### ISSUE THREAD

**Issue by builthuLin** [yangzongzhuan/RuoYi#2]
在htymeleaf里面使用内联方式[[]]，在页面初始化的时候都会预编译，所以说每次在刷新页面的时候，不管以下的判断怎么处理，thymeleaf都会根据[[]]里的处理去调用后台方法获取系统主题，这样也占用资源消耗，也体现不出local storage本地缓存的多大作用。
![image](https://user-images.githubusercontent.com/43112931/69407371-4d58fe00-0d3f-11ea-86d0-bb6bfa703ea8.png)
建议在这里不要用这种内联方式加载后台方法获取属性，直接用ajax请求略佳
![image](https://user-images.githubusercontent.com/43112931/69407530-a163e280-0d3f-11ea-927e-698dedd5ad6f.png)

**Comment by builthuLin** [comment]
[[]]内联符号很敏感，注释也不要写，一样也会预编译

**Comment by yangzongzhuan** [comment]
嗯，调整了 更新代码即可。
