### ISSUE TITLE
ruoyi-quartz 并发执行job，根据id查询，传入id=1，返回id=2 ？？？

### ISSUE THREAD

**Issue by DreamOfGypsy** [yangzongzhuan/RuoYi#202]
使用ruoyi-quartz
由Controller连续接收两次页面请求，根据fileId创建对文件A和文件B的处理，插入到SysJob中。
![新增SysJob的过程](https://github.com/yangzongzhuan/RuoYi/assets/128133094/cbca9567-7a78-49f9-9db7-16dcee71107d)
![SysJob 新增job记录](https://github.com/yangzongzhuan/RuoYi/assets/128133094/7af4a9fa-a0a7-487e-81e1-2fc235cb367d)

当两个job同时启动时，任务内部会根据fileId查询file对象。
 **当传入文件A的fileId时，查询出的file对象却是文件B？？？** 
![查询出错](https://github.com/yangzongzhuan/RuoYi/assets/128133094/42698201-c8da-4938-b76f-aa270b0f4109)
![查询mapper-xml](https://github.com/yangzongzhuan/RuoYi/assets/128133094/57f94f79-6f42-4728-8387-f32600b7a0d7)
![查询mapper-xml vo](https://github.com/yangzongzhuan/RuoYi/assets/128133094/c44be0ac-2d3b-45c2-95ad-faa6c840b2d6)

导致日志出现两条相同的记录，即两个job同时在处理同一个文件！
![两个job的运行日志](https://github.com/yangzongzhuan/RuoYi/assets/128133094/708b073f-7758-4243-b36c-5698a946001d)

 **测试过修改concurrent的值，也尝试过在xml中加入flushCache="true"以刷新缓存，均未奏效！**

**Comment by yangzongzhuan** [comment]
不分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi/issues 需要提供出能复现问题详细步骤。
