### ISSUE TITLE
前后端实现上传下载时遇到了问题？如下面的图文描述所示：

### ISSUE THREAD

**Issue by Wyt-GitHub8000** [yangzongzhuan/RuoYi#203]
前端上传了一个文件，服务器打开没有问题，但是我调用系统提供的下载接口去下载的时候，文件正常下载，但是下载excel文件打不开，下载的图片文件没内容？？
![image](https://github.com/yangzongzhuan/RuoYi/assets/72081877/9c31a18a-5868-43c5-a435-4a8a12f09fab)
![image](https://github.com/yangzongzhuan/RuoYi/assets/72081877/12c652c9-058b-42ac-a410-66d8f4799e7b)

**Comment by yangzongzhuan** [comment]
不分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi/issues

前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues

微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues
