### ISSUE TITLE
@Anonymous 针对post接口无效

### ISSUE THREAD

**Issue by freezehe** [yangzongzhuan/RuoYi#204]
如题，我最近在使用若依框架，发现 @Anonymous在post接口上不生效，我的springboot版本是：2.5.14 ，在post接口上使用[@APENG](https://gitee.com/anonymous) 注解，postman测试还是会提示401 拒绝访问。截图如下：
![image](https://github.com/yangzongzhuan/RuoYi/assets/11324122/3ead6ece-6b07-42fe-92a3-8dd252a63611)

![image](https://github.com/yangzongzhuan/RuoYi/assets/11324122/1aebd8b5-f9d5-45f9-93b0-9b8984a13953)

![image](https://github.com/yangzongzhuan/RuoYi/assets/11324122/ac2d09ae-a7c1-4d5a-b65a-63a5e3dfd5b5)

![image](https://github.com/yangzongzhuan/RuoYi/assets/11324122/c48ed636-d6d3-4aee-9822-4e9d3aea0fb7)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
