### ISSUE TITLE
侧边栏问题

### ISSUE THREAD

**Issue by jparameter** [yangzongzhuan/RuoYi#208]
我们想改一下侧边栏，就是点一下收起来的时候不显示图标，只显示两个字就可以，但是找了半天还是没找到怎么控制它收起来的时候只显示图标的代码，希望能得到一点启示
![image](https://github.com/yangzongzhuan/RuoYi/assets/43598654/276f1ad0-2f41-46a5-9ba4-c46068bd70c4)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
