### ISSUE TITLE
正常运行，登录后台，显示jwt:null

### ISSUE THREAD

**Issue by gcg888** [yangzongzhuan/RuoYi#21]
按照文档配置好，正常运行后，无法登录后台，显示如下信息，是什么原因？
6:55:27.859 [http-nio-8081-exec-14] INFO  c.r.f.s.w.f.BJwtFilter - [getToken,93] - jwt:null

**Comment by yangzongzhuan** [comment]
试了下没有你说的问题，请提供重现问题步骤。且更多错误信息和截图。
