### ISSUE TITLE
前端在views文件夹下放置scss文件会被打包为全局style

### ISSUE THREAD

**Issue by zyy9803** [yangzongzhuan/RuoYi#211]
请问为什么前端在views文件夹下放置scss文件会被打包为全局style，scope属性会失效。只要在views文件夹下放置了scss文件，即使该文件没有被import，打包时也会被编译为全局属性，导致css污染。我使用vue-cli重新生成了一个干净的项目，发现在vue-cli生成的项目中不会出现该情况。对于ruoyi项目的vue.config.js配置，我也尝试清除之后再次打包，还是会出现这种情况。请问是在哪里配置了webpack吗？该情况产生的原因是什么？

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
