### ISSUE TITLE
数据字典，字典标签输入"<"符号，会被自动转义为"&gt;"

### ISSUE THREAD

**Issue by chenzw8** [yangzongzhuan/RuoYi#212]
![image](https://github.com/yangzongzhuan/RuoYi/assets/97418958/94cc4e33-c097-44ae-8166-6e6d73aff112)
![image](https://github.com/yangzongzhuan/RuoYi/assets/97418958/845825f6-dffd-4f61-a35d-b59928f0ecc9)
请问如何才能在字典中输入"<"符号

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
