### ISSUE TITLE
若依前后端分离版本，多节点部署重启问题

### ISSUE THREAD

**Issue by donfisher** [yangzongzhuan/RuoYi#213]
![image](https://github.com/yangzongzhuan/RuoYi/assets/18061408/9c30e016-8c45-4efa-a04e-977068f025d9)

本地和单节点打包部署都正常，多节点部署的时候会报这个错，然后自动重启一次或两次后又正常

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
