### ISSUE TITLE
Converting circular structure to JSON如何解决

### ISSUE THREAD

**Issue by ionic666** [yangzongzhuan/RuoYi#216]
开发环境正常，到生产环境报错
Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '_' -> object with constructor 'Object'
    |     property 'vnode' -> object with constructor 'Object'
    |     ...
    |     property 'ref' -> object with constructor 'iZ'
    --- property '_rawValue' closes the circle
    at JSON.stringify (<anonymous>)
请问怎么解决

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。

微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues 需要提供出能复现问题详细步骤。

移动端版本问题请到这里提问 https://gitee.com/y_project/RuoYi-App/issues 需要提供出能复现问题详细步骤。
