### ISSUE TITLE
求组，本地运行正常，但是构建出来的包缺少页面资源

### ISSUE THREAD

**Issue by restart168** [yangzongzhuan/RuoYi#217]
求助，因为采用ruoyi的接口生成路由，所以本地router的route就没有引用页面文件（好像每个ruoyi项目都是这样子），但是这次构建出来的包没有相关的页面文件，想想好像也对，毕竟没有引用资源，自然就不会打包出来，但是以前构建ruoyi项目都是会打包相关资源的
![Snipaste_2023-11-07_23-37-38](https://github.com/yangzongzhuan/RuoYi/assets/67007754/29c1001a-5182-4b8c-aa87-913fdbba350c)
![Snipaste_2023-11-07_23-37-49](https://github.com/yangzongzhuan/RuoYi/assets/67007754/b2f817b1-877a-489e-852c-6fdfffcfe9a2)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
