### ISSUE TITLE
登录表单bug修复

### ISSUE THREAD

**Issue by pipipapi** [yangzongzhuan/RuoYi#218]
登录表单修复:  用户名密码的value给写死了..每次登录都要重新输入

**Comment by yangzongzhuan** [comment]
不分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi/issues 需要提供出能复现问题详细步骤。

前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。

微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues 需要提供出能复现问题详细步骤。
