### ISSUE TITLE
前端页面时不时出现页面渲染不出来

### ISSUE THREAD

**Issue by 326886472** [yangzongzhuan/RuoYi#23]
生产环境经常出现
chunk-libs.8d06862d.js:46 Error: Loading chunk chunk-489b6646 failed.
(missing: http://new_console.famy.ly/static/js/chunk-489b6646.73a176b8.js)
    at HTMLScriptElement.b (anchorScreening:184)
这种报错导致卡死

**Comment by yangzongzhuan** [comment]
请提供详细报错和重现步骤。
