### ISSUE TITLE
生成代码

### ISSUE THREAD

**Issue by lhhlzz** [yangzongzhuan/RuoYi#24]
生成代码的时候  能不能加个指定类型的

![image](https://user-images.githubusercontent.com/62694187/84999468-c4466000-b183-11ea-9674-5d701c3369eb.png)

还有  后台  字段信息   java类型 没有 Boolean类型

![image](https://user-images.githubusercontent.com/62694187/84999395-aaa51880-b183-11ea-8608-ca1a4e3f694d.png)

**Comment by yangzongzhuan** [comment]
看不到你发的截图，你贴代码吧。

**Comment by lhhlzz** [comment]
> 看不到你发的截图，你贴代码吧。
<result column="is_delete" property="deleted" jdbcType="BIT" />
对应的实体
private Boolean deleted;

还有后台生成代码段 实体类字段属性没有  Boolean类型

**Comment by lhhlzz** [comment]
`private Boolean deleted;  <result column="is_delete" property="deleted" jdbcType="BIT" />`

**Comment by yangzongzhuan** [comment]
GenConstants可以添加自己的类型。
