### ISSUE TITLE
登录的时候报用户服务调用失败

### ISSUE THREAD

**Issue by majiaqing** [yangzongzhuan/RuoYi#29]
![image](https://user-images.githubusercontent.com/54875054/88884273-d3cbc500-d268-11ea-910f-db6a75e47a49.png)
![image](https://user-images.githubusercontent.com/54875054/88884339-f2ca5700-d268-11ea-828c-6df58de08647.png)

**Comment by yangzongzhuan** [comment]
微服务版本请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues
