### ISSUE TITLE
关于路由添加

### ISSUE THREAD

**Issue by KevinBlack** [yangzongzhuan/RuoYi#3]
请问如果我想在菜单管理页面添加一个主类目的按钮，也就是左侧菜单点击直接出来个页面，需要怎么设置呢？我按照别的子组件来设置貌似不对！它打开了一个全新的页面！
<img width="591" alt="WX20191125-155117@2x" src="https://user-images.githubusercontent.com/524062/69522115-8db4b800-0f9b-11ea-9e9d-5b0425e9cbd7.png">

**Comment by bweib** [comment]
参考别的目录看看，文件夹要在主目录下的吧

**Comment by yangzongzhuan** [comment]
这个你可以更新下版本，已经支持了。
