### ISSUE TITLE
父子表的checkbox怎么解决联动问题？

### ISSUE THREAD

**Issue by mrsun123** [yangzongzhuan/RuoYi#31]
请问若依 使用bootstrapTable父子表的时候，子表已经成功显示在父表中，但父表上的checkbox无法选择到子表中的数据，父子表的checkbox怎么解决联动问题？

> 1.选择父表checkbox   子表全选   子表如果没有全选中 父表不选中
> 1.包括父表全选的时候  子表也联动全选      子表不全选中时  父表不选中  父表全选也不选中
请大神帮忙

**Comment by yangzongzhuan** [comment]
如果是父子表需要自己写事件做处理。
