### ISSUE TITLE
数据权限问题

### ISSUE THREAD

**Issue by zhoutao1** [yangzongzhuan/RuoYi#32]
一个用户有多个角色，每个角色的数据权限都不一样，这时候dataScopeFilter方法中会读取到2个不同的role的datascope，造成使用混乱

例如新建了2个角色，菜单权限不同，2个角色中包含了同一个人，数据权限都是仅限本人。这时候sql中会出现AND (u.user_id = 2 OR u.user_id = 2 ) 拼装了2次，这个算问题吗？

**Comment by yangzongzhuan** [comment]
是正常的，因为你给了他两个角色的权限。
