### ISSUE TITLE
生成代码，报模板错误

### ISSUE THREAD

**Issue by CiicDong** [yangzongzhuan/RuoYi#38]
Lexical error,   Encountered: <EOF> after : "" at vm/vue/index.vue.vm[line 515, column 0]
org.apache.velocity.exception.ParseErrorException: Lexical error,   Encountered: <EOF> after : "" at vm/vue/index.vue.vm[line 515, column 0]
下面是我的数据库字段表
![image](https://user-images.githubusercontent.com/20351235/94414734-4268c880-01af-11eb-9cf6-d2ccb4383d0b.png)
再页面上点击会出现如下的错误
哪里出错了呢？
![image](https://user-images.githubusercontent.com/20351235/94414791-56142f00-01af-11eb-8e2e-8b5f45e2eb7b.png)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问
https://github.com/yangzongzhuan/RuoYi-Vue/issues
