### ISSUE TITLE
RedisUtils依赖注入问题

### ISSUE THREAD

**Issue by undwin** [yangzongzhuan/RuoYi#47]
![HU (BXT~~)@MQFJPV FDEQ7](https://user-images.githubusercontent.com/27284024/99870332-4e03c900-2c0d-11eb-95a8-eb4d156f9417.png)
【实习】Never say die(oo528oo@17173.com) 2020/11/21 15:07:31
请问一下新建子模式引用ruoyi-common-redis，bean注入不进来喝ruoyi-system是一样的

【实习】Never say die(oo528oo@17173.com) 2020/11/21 15:07:49
有遇到过这种情况的吗

**Comment by RoeGross** [comment]
问题解决了吗？

**Comment by yangzongzhuan** [comment]
微服务版本请到这里提问
https://github.com/yangzongzhuan/RuoYi-Cloud/issues
