### ISSUE TITLE
掉了接口之后  前端发出去了  后端接收不到  登上几分钟 后端才能接到请求  是怎末回事呀

### ISSUE THREAD

**Issue by kang-N-S** [yangzongzhuan/RuoYi#51]
就是上传文件或者图片的接口就是这样
![image](https://user-images.githubusercontent.com/50577873/100432965-4e043d00-30d5-11eb-82e5-0c28e3f03b20.png)这个shi是版本

**Comment by yangzongzhuan** [comment]
那只可能是你网络有问题了，或升级版本试试。
