### ISSUE TITLE
发现一个BUG，自动生成的代码中复选框bug

### ISSUE THREAD

**Issue by beicky** [yangzongzhuan/RuoYi#58]
数据回显时，复选框用`th:attr="checked=${oldMan.medicalHistory.contains(dict.dictValue)?true:false}"`判断是不是选中，contains是在字符串中查找字符串，如果找到就是true。
如果数据回显数据为123，那么会选中值为1，2，3，12，23，123这6个值，正确的是只选中值为123的选项，望修改

**Comment by beicky** [comment]
目前的解决方法是在controller里面，给回显的值前后都加个`, `
123就变为`,123,  `
1,2,3,123 就变为`,1,2,3,123, `
代码改成`th:attr="checked=${oldMan.medicalHistory.contains(','+dict.dictValue+',')?true:false}"`
这个办法很蠢，不知道有没有更好的解决方法

**Comment by yangzongzhuan** [comment]
contains不会出现你说的问题。
