### ISSUE TITLE
select2组件配置ajax后，无法触发远程加载数据

### ISSUE THREAD

**Issue by HoldDon** [yangzongzhuan/RuoYi#59]
// select2复选框事件绑定
    if ($.fn.select2 !== undefined) {
        $.fn.select2.defaults.set( "theme", "bootstrap" );
        $("select.form-control:not(.noselect2)").each(function () {
            $(this).select2().on("change", function () {
                $(this).valid();
            })
        })
    }
在select2中配置ajax后，由于common.js中绑定了一个change事件，导致远程数据无法加载。
初次使用select2并想要使用远程加载数据时，可能会造成困扰。
目前我的解决方案是把绑定事件注释掉。

**Comment by yangzongzhuan** [comment]
有需要可以自己调整。
