### ISSUE TITLE
用户查询大问题

### ISSUE THREAD

**Issue by george-clooney** [yangzongzhuan/RuoYi#6]
当我一个用户有4个角色 ，我用户集合有8条 这样我left join 角色表会查出11条 进行了分页 ，恰好那有四个角色的用户查询在上面 那么我userList的不会出现8条数据，只有7条，因为分页了下个用户在下一页，那个用户有三个角色的映射到了用户的roles里面了

**Comment by yangzongzhuan** [comment]
这个问题我记得改过，你更新下版本试试。

**Comment by george-clooney** [comment]
请问改的是哪部分，我已经改了部分源码不能随意更新了
