### ISSUE TITLE
table的$.table.search请求失败后，再次点击没有努力加载动画

### ISSUE THREAD

**Issue by spadek-w** [yangzongzhuan/RuoYi#60]
通过文档使用$.table.search时
`
<a onclick="$.table.search();">搜索</a>
`
我的场景有下面几个步骤
1. 一个筛选查询  接口响应慢，table显示正在努力加载
2.  所以我重新筛选  点击搜索 重新请求  上个请求中断  页面显示没有找到匹配的记录
3.  但是此时 重新请求table的加载动画没有显示。  接口响应有些时间，一直显示没有找到匹配的记录

**Comment by yangzongzhuan** [comment]
无法复现的问题。
