### ISSUE TITLE
前端SQL注入漏洞问题

### ISSUE THREAD

**Issue by guozhenqianga** [yangzongzhuan/RuoYi#61]
前端若依版本 3.3.0，项目部署到甲方之后，甲方网关检测出SQL注入漏洞问题，想问下怎么解决
![image](https://user-images.githubusercontent.com/23112360/105273941-3037ed80-5bd7-11eb-8d67-04067372aace.png)
![image](https://user-images.githubusercontent.com/23112360/105273968-3fb73680-5bd7-11eb-8199-aa8b8b8547bf.png)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问
https://github.com/yangzongzhuan/RuoYi-Vue/issues
