### ISSUE TITLE
【老系统融入若依不舒服的地方-建议升级下这个地方】

### ISSUE THREAD

**Issue by jklliang** [yangzongzhuan/RuoYi#65]
目前我将原有的系统升级到了若依，期间遇到几个问题，建议升级下，若依很简洁，但是融合升级老系统略麻烦。
问题：
1. 我不能把若依数据库，放入原本杂乱业务系统数据库。
2. 业务系统可以重做管理端，但是老系统service、dao层已经有复杂的业务逻辑、api等，我不能完全重写service、dao，api需要保留。
3.由于很多业务逻辑功能重构不现实，因此无法完全采用若依的基础框架、common等无法引入。很多冲突。
问题还有很多，最终解决下来：
1.采用了微服务版本。
2.完全采用了若依管理端能力。
3.业务系统cloud部分跟若依微服务版本进行了统一，完全升级spring cloud + nacos
4.业务系统提供针对若依的服务，提供给若依vue调用。
5.代码生生成，对生成controller部分进行了小的改造，生成了直接对接我们原有service、dao的功能。不使用若依生成的service、mapper

目前大致根据上面操作来改造的，但是有几个问题：
1.业务系统提供给若依管理的controler，日志记录、权限功能无法用。
![图片](https://user-images.githubusercontent.com/20180064/108084124-cf54e580-70ae-11eb-9250-40abd27f8ae7.png)
这两个服务，需要引入若依java端所有的功能。业务系统引入对基础框架入侵较大，产生很大的耦合度。
建议：这两个注解提供一个微服务版，通过调用若依system接口实现记录日志和鉴权。避免业务系统跟权限控制系统的耦合。

2.业务系统也有自己的oauth2、session等功能，是提供给app端的。目前跟若依的安全管理是冲突的，因此若依微服gateway无法成为一个全局的统一入口。这样管理端和app端api入口是分离的，需要维护两套gateway,目前没想到好的解决方案。

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问
https://github.com/yangzongzhuan/RuoYi-Cloud/issues
