### ISSUE TITLE
更新ruoyi-ui 3.4.0 npm报错

### ISSUE THREAD

**Issue by mengxin-FE** [yangzongzhuan/RuoYi#67]
![微信截图_20210224100911](https://user-images.githubusercontent.com/14139852/108935397-96a5a500-7688-11eb-8236-0b6ef1c4b0e6.png)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问
https://github.com/yangzongzhuan/RuoYi-Vue/issues
