### ISSUE TITLE
ruoyi找不到net.sf.ehcache.CacheManager的类文件

### ISSUE THREAD

**Issue by ycy980903** [yangzongzhuan/RuoYi#68]
![图片](https://user-images.githubusercontent.com/79618013/109096939-6e39ab80-7759-11eb-88c0-cd930ade0ff7.png)
我从我的电脑上把项目copy到另一台电脑上,就报这个错,错误就在当前页面,谢谢大牛指导

**Comment by yangzongzhuan** [comment]
这个是maven的问题。多更新几次试试
