### ISSUE TITLE
系统管理下全部菜单 F5刷新 报令牌不能为空

### ISSUE THREAD

**Issue by skntl9** [yangzongzhuan/RuoYi#74]
系统管理下全部菜单 F5刷新 报令牌不能为空，在标签栏右键可以刷新，
其他菜单可以F5刷新，
![image](https://user-images.githubusercontent.com/21214572/118943314-15f3fd80-b986-11eb-871d-d0c7a52bfd78.png)

**Comment by yangzongzhuan** [comment]
无法复现的问题，你可以用最新版本代码试试。
