### ISSUE TITLE
如何根据url地址，设置数据权限。

### ISSUE THREAD

**Issue by linbren** [yangzongzhuan/RuoYi#81]
如题，适用多级服务管理。例：
ruoyi.vip
ruoyi.vip/areaA
ruoyi.vip/areaB
ruoyi.vip/areaC
不同地区，对应各自的数据权限，即URL决定数据范围。
一个用户，可以在不同的URL上注册登录（实际是统一管理，但给用户的感觉是使用不同的系统），这个用户又可以配置不同子地区的权限，如可以给他配置areaA1,areaA5的权限。

**Comment by yangzongzhuan** [comment]
不支持这种方式，得需要自己去实现了。
