### ISSUE TITLE
4.6.2版本，生成的代码，无论是树表还是单表，ID字段显示不出来，传到后台为undefined。

### ISSUE THREAD

**Issue by linbren** [yangzongzhuan/RuoYi#82]
4.6.2版本，生成的代码，无论是树表还是单表，ID字段显示不出来，传到后台为undefined。 编辑、删除500错。
![image](https://user-images.githubusercontent.com/13880474/124728595-4eee2e80-df42-11eb-8a74-0fe855835323.png)

16:34:38.055 [http-nio-80-exec-2] ERROR c.r.f.w.e.GlobalExceptionHandler - [notFount,63] - 运行时异常:
org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "undefined"
	
Caused by: java.lang.NumberFormatException: For input string: "undefined"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Long.parseLong(Unknown Source)
	at java.lang.Long.valueOf(Unknown Source)

**Comment by linbren** [comment]
ID字段大小写问题

**Comment by yangzongzhuan** [comment]
应该是字段规范问题，导致值没有读取到出现了`undefined`
