### ISSUE TITLE
登录页验证码显示不出，gateway报错 [网关异常处理]请求路径:/api/code,异常信息:404 NOT_FOUND

### ISSUE THREAD

**Issue by sevenEleven-x** [yangzongzhuan/RuoYi#84]

**Comment by fujiangchao** [comment]
配置文件 放过验证码
![image](https://user-images.githubusercontent.com/80743364/129707888-2931675e-3b8f-4ef0-a7d6-8f72841ecfe1.png)

**Comment by yangzongzhuan** [comment]
测试正常，没有你说的问题。
