### ISSUE TITLE
主题设置后，刷新按钮颜色未同步

### ISSUE THREAD

**Issue by wangyangyangyang** [yangzongzhuan/RuoYi#88]
布局设置-保存设置
![1630309800(1)](https://user-images.githubusercontent.com/20415998/131304946-bc66f67a-6d19-4a3e-adea-94a7aa2232c1.png)
刷新页面后，只有tagsView和侧边栏的样式同步变化了，按钮复原了
![1630309837(1)](https://user-images.githubusercontent.com/20415998/131305034-9ee9eaff-c6ad-440f-8afc-8f701f8e5672.png)
定位是这个element-variables 文件的问题，求问这里该如何更改

**Comment by yangzongzhuan** [comment]
最新版本已经支持同步主题了。
