### ISSUE TITLE
RuoYi-Cloud 版本更新问题

### ISSUE THREAD

**Issue by TangGV** [yangzongzhuan/RuoYi#89]
70多天前clone的项目作为基础项目，今天发现项目已经迭代了很多次，同步代码后一堆类 比如system下的某些类移动到了comm-api下，幸亏我们也没改什么，发现合并起来异常的难受，还有nacos 的配置，比如白名单的前缀也改了，这样更新很让人难受啊

**Comment by yangzongzhuan** [comment]
没办法，有些优化是必须的。自己根据实际情况合并就好。
