### ISSUE TITLE
用户增加大问题-双击

### ISSUE THREAD

**Issue by hcen1997** [yangzongzhuan/RuoYi#91]
使用select count 查找 方式确认唯一性和使用mysql插入异常方式确认唯一性有区别

select count会出bug, 居然真的让我在业务中碰上了

浏览器按钮触发http请求, 执行关联的java和sql语句
以下是system:user:add中的相关代码
---
if (SqlOption.checkUserName())  
else if (SqlOption.checkPhoneUnique())  
else if (SqlOption.checkEmailUnique())  
user.setCreateBy(SecurityUtils.getUsername());  
user.setPassword(SecurityUtils.encryptPassword(user.getPassword()));  
return toAjax(userService.insertUser(user));  
---
---
 select count(1)
        from sys_user
        where user_name = #{userName}
        limit 1
---

问题就是多次点击新增按钮的时候, 会添加2条记录, 如果数据库没有唯一限制的话, 会重名

用户双击鼠标的时间大概在100ms左右, 新增用户的时间也是100ms
那么就有可能在上一次请求还在checkEmail的时候, 下一条已经过了checkUserName阶段
那么, 就造成了两次insert发生

建议解决方法: 数据库加唯一索引, 第二条报错
或者按钮做特效

**Comment by yangzongzhuan** [comment]
对于这种情况建议加一下防重复提交注解`@RepeatSubmit`，也可以在前端提交前按钮属性使用`loading`加载属性。
当然也可以自己加一下数据库加一下唯一索引。

**Comment by hcen1997** [comment]
用redis map 和spring拦截器做重复提交的校验, 我觉得没啥问题,
