### ISSUE TITLE
cloud版本如何集成oauth2

### ISSUE THREAD

**Issue by dang90324** [yangzongzhuan/RuoYi#92]

**Comment by dang90324** [comment]
集成原生的Oauth2，建立自己的第三方认证中心，来管理自己开发的api权限，如何与原来的登录认证共存

**Comment by yangzongzhuan** [comment]
参考项目扩展，里面有Oauth2版本。 http://doc.ruoyi.vip/ruoyi-cloud/document/xmkz.html
RuoYi-Cloud_Oauth2.0
