### ISSUE TITLE
其他包的bean是怎么扫描到的啊

### ISSUE THREAD

**Issue by sad-nickname** [yangzongzhuan/RuoYi#98]

**Comment by yangzongzhuan** [comment]
如果业务模块和项目的包名不一致，需要在启动类上指定扫描包路径，如 `@SpringBootApplication(exclude = { DataSourceAutoConfiguration.class }, scanBasePackages = { "com.ruoyi.*", "com.test.*" }) `或者加上`@ComponentScan({ "com.ruoyi.*", "com.test.*" })
`
